version: '3.8'

services:
  postgres:
    container_name: master-src-postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: '@gogococoadev'
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: